### ISSUE TITLE
How to get edge detection results?

### ISSUE THREAD

**Issue by playerkk** [leduoba/LEP#1]
How to recover edge detection results from segs? Additionally, what do ep1.mat and ep2.mat store?

Thanks a lot.

**Comment by leduoba** [comment]
In the BSDS500 bench package, there's a script seg2bdry.m with which you can recover edges.

ep1~2.mat are prior probability maps for contours between neighbor pixels. We collect them from the BSDS500 train images. Although we believe it is a meaningful design, but still are a little disappointed to find they are not v helpful to the final results.

Best,
Qiyang

From: Huaizu Jiang
Date: 2017-03-26 12:24
To: leduoba/LEP
CC: Subscribed
Subject: [SPAM] [leduoba/LEP] How to get edge detection results? (#1)
How to recover edge detection results from segs? Also, what do ep1.mat and ep2.mat store?
Thanks a lot.

**Comment by playerkk** [comment]
Thanks. I can now get edge detections using the seg2bdry function.

Since I see some hard coded parameters in the lepseg function (such as ep1, ep2, aw, etc), I was wondering if the code could be applied to an arbitrary image, whose dimension might be different from the one in the BSDS dataset.

**Comment by leduoba** [comment]
Yes you can, because they will be resized according to input images each time. A team from ETH Zurich applied it on Pascal VOC in ECCV 16 COB. The hard paras fit well but you may need a more powerful contour source than the random forest one we used for BSDS.

Good luck.
